### PR TITLE
Add a new file to store local development server information

### PR DESCRIPTION
**Pull request by bebaps**
- Also created a core config.js file
- This serves as the example file, and can be used in the future to store configurations should the current webpack file grow out of hand

### CODE REVIEW

**Comment by bebaps** [comment]
### Updates made to the build process

Created a new `config.js` file, and moved the proxy to that file instead of the `webpack.mix.js`.

```
// .config.js

// Create a duplicate of this file and rename it to config.local.js
// Use this file to store any config unique to your local development setup
module.exports = {
  proxy: 'https://my-local-dev.site'
};
```

```
// ./webpack.mix.js

const config = require('./config.local.js');
const mix = require('laravel-mix');

...
mix.browserSync({
  proxy: config.proxy,
  files: ['assets/js/**/*.js', 'assets/css/**/*.css'],
  stream: true,
});
```

The current setup does not account for team members using different local development environments. The way it is currently setup, I would need to either never commit my change to `webpack.mix.js` or just remember to change it back in the final commit before the PR. Since we don't know who will be working on this project in the future or what local dev they will be using, I think this small change will make it easy to customize from the beginning.

## Other changes

The `readme.md` has been updated to provide directions for this change. The `.gitignore` has also been updated to ignore `config.local.js`.

**Comment by bebaps** [comment]
This update was a part of other PRs, but it is now extracted into its own PR.

**Review by mlsamuelson — APPROVED** [review]
A nice improvement to have. Thanks @bebaps.

@tbutterf Can you review as well. This impacts the PR you have open with the README.md  updates for the Renovation theme.  If you approve as well, you're good to merge.

**Review by tbutterf — APPROVED** [review]
This is a great idea @bebaps. I noticed the problem, but hadn't come up with a solution. Awesome work!

**Pull request merged**
