### PR TITLE
WS2-1175: Fix ASU Brand Header.

### PR DESCRIPTION
**Pull request by georgebaev**
@duarte-daniela @mlsamuelson This fixes the ASU Brand Header.

Ref.: https://asudev.jira.com/browse/WS2-1175

### CODE REVIEW

**Comment by mlsamuelson** [comment]
It looks like https://stable-v3-dept-stable-release.ws.asu.edu/ has been updated with these changes? If correct, this is what I see: 

* [FIXED] Column headings in drop down menus are wrong shade of gray. Probably a style from the theme bleeding through.
* [NOT FIXED] At the mobile screen size, the close button for the mobile menu looks squashed.
* [FIXED] There is a gap under the global menu at desktop size.
* [NOT FIXED] Spacing styles for the mobile menu's "footer" are off. 

I wanted to note: The style fixes here have been made in the theme, instead of the CSS file with the ASU Brand module. I've been trying to keep the styles for the header in the module so it could be used in a non-Webspark project. No one is doing that yet, but in the past, use cases like that have come up. I'm okay with the styles being in the theme, but wanted to explain why the original styles are in the module. I'll leave it to you to decide where they belong. If the fixes here are to address compatibility issues with Webspark, it makes sense to have them in theme. If they are to address compatibility issues with Drupal in general, maybe the module is a better place.

Also, in that site the header logo isn't loading. Gives a 404. @duarte-daniela I think this is an asset loading issue, like we had with the image assets used in the app-degree-pages component in ASU Degree RFI module.

**Comment by georgebaev** [comment]
@mlsamuelson I use the template at https://unity.web.asu.edu/@asu-design-system/component-header/iframe.html?id=uds-asu-header--with-mobile-nav-tree&args=&viewMode=story as a reference and I don't see problems which were not fixed at https://stable-v3-dept-stable-release.ws.asu.edu/ .

Could you please submit screenshots of the problems which haven't been fixed yet?

**Comment by georgebaev** [comment]
@mlsamuelson I think that these changes should be kept in the theme because they address issues caused by the `renovation` theme. I use the `..block--asubrandheader` CSS selector as a wrapper to ensure that the changes reference the ASU Brand Header Drupal component only.

**Comment by mlsamuelson** [comment]
@georgebaev If that's the case, I would be good keeping them in the theme. :) I just wanted to make sure.  Since it's closed now, maybe you have another plan? 👍🏼

**Comment by georgebaev** [comment]
@mlsamuelson yes, it seems that there are problems in displaying the ASU Brand header in sub-themes so we decided to move the formatting in the module, https://github.com/ASUWebPlatforms/webspark-module-asu_brand/pull/15 . That's why I closed this PR. 

cc @dan-poenaru-dept

**Pull request closed without merging**
