### PR TITLE
WS2-1277: Edit README.md

### PR DESCRIPTION
**Pull request by tbutterf**
Hi Michael. I did a pretty thorough examination of the files in Renovation versus what is in Unity, and I have found some discrepancies. I have moved several files into a new directory. Many of these files do not seem to be in use, and I recommend that we delete them. The new directory is src/sass/renovation-extends. It contains the following:
x _blockquotes_old.scss
x _icons.scssx
x _media-crop.scss
y _media_embed.scss
y _tabs.scss
y _testimonials.scss
x _testimonials_old.scss
x _testimonials_old.scss.old
x _typography.scss (commented out)

As you can see, I have prepended each file name with an "x" or a "y." The "x" files do not seem to be in use in the theme, and probably can be deleted. The "y" files are in use. I moved them out from the src/extends directory so that it would be easier to keep track of the files that are NOT in Unity, but are being used by Renovation. The only exception to this is the _tabs.scss file in the variables directory. It doesn't exist in Unity, but it does exist in Renovation. I thought about moving it, but there is already a _tabs.scss file in the new renovation-extends directory. We could move its contents into the base/_variables.scss file, if we want, or just add the file to the base/ directory. That might make it easier, if it is separated from the other files in the variables folder which match 1:1 with what is in Unity.

Anyway. On top of those things, I have completely rewritten the readme file. Please feel free to reject any and all of the text that I have used, or to suggest further changes. But, I'm hoping it will help make things clearer for people moving forward. Please let me know if you have any questions.

### CODE REVIEW

**Comment by tbutterf** [comment]
Here is the Jira ticket: (https://asudev.jira.com/browse/WS2-1277)

**Comment by bebaps** [comment]
I have no issues with the requested changes. There may need to be a small change if my PR is merged in, but in general looks good!

**Review by bebaps — APPROVED** [review]
Reviewed changes and all looks good!

**Comment by mlsamuelson** [comment]
@tbutterf In light of https://github.com/ASUWebPlatforms/webspark-theme-renovation/pull/312 being merged, I believe there may be a few tweaks to make to the README.md regarding configurations for local dev.

**Review by mlsamuelson — APPROVED** [review]

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
Marking for review again, as re-reading the initial comment from @tbutterf there are some decisions to be made before this is merged.

> As you can see, I have prepended each file name with an "x" or a "y." The "x" files do not seem to be in use in the theme, and probably can be deleted. The "y" files are in use. I moved them out from the src/extends directory so that it would be easier to keep track of the files that are NOT in Unity, but are being used by Renovation. The only exception to this is the _tabs.scss file in the variables directory. It doesn't exist in Unity, but it does exist in Renovation. I thought about moving it, but there is already a _tabs.scss file in the new renovation-extends directory. We could move its contents into the base/_variables.scss file, if we want, or just add the file to the base/ directory. That might make it easier, if it is separated from the other files in the variables folder which match 1:1 with what is in Unity.

Let's keep the x_'s on files we think aren't used, so we can verify and later delete. For those in use, we don't need a y_ in front of them, so please remove.

For the _tabs.scss issue, the base/_variables.scss is coming from Unity, right? If yes, then we don't want to interfere with that. We may need to discuss more about how to cleanly solve for this.

**Comment by travisbutterfield** [comment]
@mlsamuelson I didn't add the "x" and "y" to the actual file names, just to the list in my initial comment. One of the files already had an "x" appended to the end of the file extension, but I didn't do that. Would you like me to add the "x" to the ones we want to delete? 

As for the _tabs.scss issue, you are right. I think that was a mistake on my part. I wonder if a good solution would be to create another directory named renovation_variables and put the _tabs.scss file into that?

**Comment by mlsamuelson** [comment]
@travisbutterfield I like the `renovation_variables` solution. It maintains a parallel approach with Unity and what you've done with the `renovation-extends` folder.

Ahh, leaving the file names as they currently are is good. :D

**Review by mlsamuelson — APPROVED** [review]

**Review by bebaps — COMMENTED** [review]
Looking good.

**Pull request merged**
