### PR TITLE
WS2-813: Video Hero max width

### PR DESCRIPTION
**Pull request by bebaps**
First part of this complete. Set the video hero block to have a `max-width: 1920px`. Also removed the `padding-left: 0` that was causing the text to hug the left side on smaller screens and be misaligned with the text/blocks farther down the page.

This also includes the same changes I made in another PR so enable developers to use whatever `proxy` value is needed locally without major workflow disruptions.

### CODE REVIEW

**Comment by bebaps** [comment]
Jira ticket: https://asudev.jira.com/browse/WS2-813

**Comment by bebaps** [comment]
PR outlining workflow changes: https://github.com/ASUWebPlatforms/webspark-theme-renovation/pull/198

**Comment by mlsamuelson** [comment]
@dan-poenaru-dept @ovista-dept @duarte-daniela Wondering if one or more of you could review this to be included in the next release.

**Comment by duarte-daniela** [comment]
I close this PR since this was fixed from UDS. @bebaps @mlsamuelson @imorale2

**Comment by duarte-daniela** [comment]
@bebaps I just realised that this PR include some improvements (This also includes the same changes I made in another PR so enable developers to use whatever proxy value is needed locally without major workflow disruptions.) Could you create a PR with only this change? That will be great!

@mlsamuelson

**Comment by bebaps** [comment]
@duarte-daniela sorry I am really late to this. These notifications are getting lost with the other repos, I will work on that. But yea I will create a new PR with just that one change shortly.

**Pull request closed without merging**
