### PR TITLE
WS2-603: Fix tooltip display in iPhone.

### PR DESCRIPTION
**Pull request by georgebaev**
@duarte-daniela @mlsamuelson this fixes the toolitp display in iPhone.

Ref.: https://asudev.jira.com/browse/WS2-603?focusedCommentId=1397188

### CODE REVIEW

**Review by mlsamuelson — COMMENTED** [review]
Does this duplicate the fixes from UDS? : https://github.com/ASU/asu-unity-stack/pull/653?notification_referrer_id=NT_kwDOAAM8o7EyNzY3NDI3NzMyOjIxMjEzMQ#pullrequestreview-823463739

**Comment by georgebaev** [comment]
@mlsamuelson yes, this duplicates the fixes from https://github.com/ASU/asu-unity-stack/pull/653

**Comment by mlsamuelson** [comment]
@georgebaev Does it need to be committed along with [ASU/asu-unity-stack#653](https://github.com/ASU/asu-unity-stack/pull/653) or does that PR alone solve the issue?

**Comment by georgebaev** [comment]
@mlsamuelson yes, we need this change in the Renovation theme also.

**Comment by duarte-daniela** [comment]
@mlsamuelson I was checking, this PR is fine, it is how we import the unity fixes. The only thing is that unless it is an emergency, we wait for it to be approved and released in UDS before importing it.

cc: @georgebaev

**Review by mlsamuelson — APPROVED** [review]

**Pull request merged**
