### PR TITLE
WS2-896: Updates to Layout Builder field descriptions

### PR DESCRIPTION
**Pull request by bebaps**
This PR includes two updates to Renovation:

**Updates made to the block configuration form via the theme.**

- Removed the background and border styles.
- Adjusted font color.
- Reduced font-size 2px to easily tell difference between Label vs Description.

I think it would be more ideal however to not use CSS overrides, but instead move these styles to a class, and then add this class to the output of the description classes. I was not able to determine if the Renovation theme is providing an override for this area, so for the time being I will stick to the overrides.

Screen Shot 2021-08-23 at 12 09 09 PM

<hr>

**Updates made to the build tools and README**.

Created a new `config.local.js` file, and moved the `proxy` to that file instead of the `webpack.mix.js`.

```
// .config.local.js

module.exports = {
    proxy: 'local-dev-environment-url'
};
```

```
// ./webpack.mix.js

const config = require('./config.local.js');
const mix = require('laravel-mix');

...
mix.browserSync({
  proxy: config.proxy,
  files: ['assets/js/**/*.js', 'assets/css/**/*.css'],
  stream: true,
});
```

I am not using the same local dev environment as the others. The way it is currently setup, I would need to either never commit my change to `webpack.mix.js` or just remember to change it back in the final commit before the PR. Since we don't know who will be working on this project in the future or what local dev they will be using, I think this small change will make it easy to customize from the beginning.

### CODE REVIEW

**Comment by bebaps** [comment]
Link to Jira: https://asudev.jira.com/browse/WS2-896

**Comment by mlsamuelson** [comment]
@dan-poenaru-dept @ovista-dept @duarte-daniela Wondering if one or more of you could review this to be included in the next release.

**Comment by imorale2** [comment]
@bebaps we are trying to clean up our commits, do you mind updating this commit so we can check it and merge it, finally? Sorry for the delay.

**Comment by bebaps** [comment]
@imorale2 just seeing this, yea I will knock that out.

**Comment by bebaps** [comment]
@imorale2 @mlsamuelson finally got around to this. I pulled in the changes from the `main` branch, so should no longer have any conflicts. Final CSS will still need to be compiled for your QA.

**Comment by bebaps** [comment]
I also removed the workflow changes I had suggested, as those are now isolated to their own PR.

**Review by mlsamuelson — APPROVED** [review]
Thank you!

**Pull request merged**
