### PR TITLE
Blockquote image size (latest update from unity)

### PR DESCRIPTION
**Pull request by duarte-daniela**

### CODE REVIEW

**Comment by deptant** [comment]
Image on the left is 180px. This changes image on the right to be 72px. That seems odd to me. Removing this override works but displays the image at 180px.

**Comment by mlsamuelson** [comment]
@imorale2 Do you have any insights into this issue and a recommended path?

**Comment by duarte-daniela** [comment]
Hi @mlsamuelson! the original override was not necessary, but when I did deeper tests there was an issue related to a style which  we only have in Drupal (sets a max-with of 700px for the paragraphs), this affected the blockquotes when they had an image positioned on the right. I checked this change with UDS team. Let me know if you have any questions.

**Review by mlsamuelson — APPROVED** [review]
Sounds like you've already aligned with the UDS devs on this approach. That's all I wanted to ensure. Thanks, @deptant

**Pull request merged**
