### PR TITLE
Removing img and css for ckeditor anchor icon (undo of WS2-1102)

### PR DESCRIPTION
**Pull request by chill5-0**
Moved this to the webspark_ckeditor_plugins module so the anchor appears in ckeditor regardless of the current theme.

### CODE REVIEW

**Review by mlsamuelson — COMMENTED** [review]
Changes look alright - but should we include assets/css/renovation.style.css in this? We usually do the css build at the end of the release.

**Comment by chill5-0** [comment]
Good question - I'd say not to include the compiled CSS in the commit, until we do an official release, because that's covered in the readme. Should I remove those files from the commit?

**Comment by mlsamuelson** [comment]
@chill5-0 Yes please. Just the compiled css needs to be removed. The scss should remain.

**Comment by chill5-0** [comment]
I accidentally deleted the files, then restored the original from main. Just wanted to make sure it's now ok to merge.

**Review by mlsamuelson — APPROVED** [review]

**Comment by mlsamuelson** [comment]
@chill5-0 Okay to merge when you're ready.

**Pull request merged**
